GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
GOGET=$(GOCMD) get
BINARY_NAME=tryte-crypt-go
LINTER=golangci-lint

all: test build

test: $(GOTEST) ./tests -v

build: $(GOBUILD) -o $(BINARY_NAME) -v

lint: $(LINTER) run
